# Section A: Data Structures & Control Structures

# Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [27]:
Lst1=[23,34,45,56,67]

In [28]:
#append
Lst1.append(69)
Lst1

[23, 34, 45, 56, 67, 69]

In [29]:
#extend
Lst1.extend([78,89])
Lst1

[23, 34, 45, 56, 67, 69, 78, 89]

In [30]:
#insert
Lst1.insert(0,44)
Lst1

[44, 23, 34, 45, 56, 67, 69, 78, 89]

In [31]:
#remove
Lst1.remove(45)
Lst1

[44, 23, 34, 56, 67, 69, 78, 89]

In [32]:
#pop--removes the element at the mentioned index position
Lst1.pop(0)
Lst1

[23, 34, 56, 67, 69, 78, 89]

In [33]:
Lst1.pop() #removes the last element
Lst1

[23, 34, 56, 67, 69, 78]

In [36]:
Lst1.index(23) # gives the index position of 2nd element in list

0

In [37]:
Lst1.count(34)  # element 3 is present once

1

In [38]:
# sort & reverse
Lst1.sort(reverse=True)
Lst1

[78, 69, 67, 56, 34, 23]

In [39]:
#sort
Lst2=Lst1
Lst2.sort()
Lst2

[23, 34, 56, 67, 69, 78]

In [40]:
#clear
Lst2.clear()
Lst2

[]

# Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [41]:
tuple=('Mallikarjun','Sujal','Koti')
tuple

('Mallikarjun', 'Sujal', 'Koti')

In [42]:
tuple[1]='Harsha'

TypeError: 'tuple' object does not support item assignment

Explaination: Tuples are immutable in nature,So we can't change once it's created

# Create a set of integers with some duplicate values. Print the set and explain the output

In [43]:
set = {5,4,3,1,1,3,3,4,6,7,8,9}
set

{1, 3, 4, 5, 6, 7, 8, 9}

Explaination: Set is an unordered collecction of elements, if it contains any duplicate means python will remove it by default

# Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [44]:
dict={'name': 'Mallikarjun','age':21,'city':'Alnavar'}
dict

{'name': 'Mallikarjun', 'age': 21, 'city': 'Alnavar'}

In [45]:
dict['age']=25
dict

{'name': 'Mallikarjun', 'age': 25, 'city': 'Alnavar'}

In [46]:
dict['email']='mallu76@gmail.com'
dict

{'name': 'Mallikarjun',
 'age': 25,
 'city': 'Alnavar',
 'email': 'mallu76@gmail.com'}

# Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [47]:
age=int(input('enter your age'))
if age>=18:
    print('eligible to vote')
else:
    print('not eligible')

enter your age 11

not eligible

# Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [48]:
Marks=int(input('enter the marks'))
if Marks >= 90:
    print("Grade A")
elif Marks >=75:
    print("Grade B")
elif Marks >=50:
    print("Grade C")
else:
    print("fail")

enter the marks 65

Grade C

# Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [51]:
n=int(input('enter number'))
if n>0:
    if n % 2==0:
        print(n,"is positive and even")
    else:
        print(n, "is positive and odd")
elif n == 0:
    print('number is zero')
else:
    print(n,' is odd')

enter number 1

1 is positive and odd

# NUMPY

# Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [53]:
import numpy as np
scalar=np.array(5)
scalar

array(5)

In [54]:
#1D array
one_dim=np.array([5,6,7,8,9,1])
one_dim

array([5, 6, 7, 8, 9, 1])

In [63]:
#2D array
two_dim=np.arange(10,61,10).reshape(2,3)
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [64]:
#2D in manual way
two_dim1=np.array([[2,3,4],[3,5,6]])
two_dim1

array([[2, 3, 4],
       [3, 5, 6]])

# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [66]:
a=np.random.randint(0,100,size=(4,4))
a

array([[94, 77, 19, 93],
       [ 0, 85, 59, 32],
       [34, 95, 81, 59],
       [62, 39, 56, 70]], dtype=int32)

# Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [67]:
import pandas as pd
two_dim2= np.array([[1,2,3],[4,5,6],[7,8,9]])
two_dim2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
df=pd.DataFrame(two_dim2, columns=['a','b','c'])
df

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

# PANDAS

# Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [74]:
data = {
    'Name': ['Mallikarjun', 'Sujal', 'Koti', 'Sank', 'Prajwal', 'Abhi', 'Harsha', 'Geeta', 'Jaya', 'Rakshith'],
    'Age': [33, 25, 38, 30, 23, 58, 27, 32, 45, 25],
    'City': ['Bengaluru', 'Delhi', 'Bengaluru', 'Chennai', 'Mumbai', 'Delhi', 'Bengaluru', 'Delhi', 'Bengaluru', 'Delhi'],
    'Salary': [20000, 550000, np.nan, 40000, 78000, np.nan, 66000, 50000, 100000, 50000]
}
df = pd.DataFrame(data)

In [75]:
df

          Name  Age       City    Salary
0  Mallikarjun   33  Bengaluru   20000.0
1        Sujal   25      Delhi  550000.0
2         Koti   38  Bengaluru       NaN
3         Sank   30    Chennai   40000.0
4      Prajwal   23     Mumbai   78000.0
5         Abhi   58      Delhi       NaN
6       Harsha   27  Bengaluru   66000.0
7        Geeta   32      Delhi   50000.0
8         Jaya   45  Bengaluru  100000.0
9     Rakshith   25      Delhi   50000.0

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [77]:
df.describe

<bound method NDFrame.describe of           Name  Age       City    Salary
0  Mallikarjun   33  Bengaluru   20000.0
1        Sujal   25      Delhi  550000.0
2         Koti   38  Bengaluru       NaN
3         Sank   30    Chennai   40000.0
4      Prajwal   23     Mumbai   78000.0
5         Abhi   58      Delhi       NaN
6       Harsha   27  Bengaluru   66000.0
7        Geeta   32      Delhi   50000.0
8         Jaya   45  Bengaluru  100000.0
9     Rakshith   25      Delhi   50000.0>

In [78]:
df_name_city = df[['Name', 'City']]
df_name_city

          Name       City
0  Mallikarjun  Bengaluru
1        Sujal      Delhi
2         Koti  Bengaluru
3         Sank    Chennai
4      Prajwal     Mumbai
5         Abhi      Delhi
6       Harsha  Bengaluru
7        Geeta      Delhi
8         Jaya  Bengaluru
9     Rakshith      Delhi

In [79]:
df_drop = df.drop('City',axis=1)

In [80]:
df_drop

          Name  Age    Salary
0  Mallikarjun   33   20000.0
1        Sujal   25  550000.0
2         Koti   38       NaN
3         Sank   30   40000.0
4      Prajwal   23   78000.0
5         Abhi   58       NaN
6       Harsha   27   66000.0
7        Geeta   32   50000.0
8         Jaya   45  100000.0
9     Rakshith   25   50000.0

In [81]:
sal_mean=df['Salary'].mean()

In [82]:
df['Salary'] = df['Salary'].fillna(sal_mean)

In [83]:
df

          Name  Age       City    Salary
0  Mallikarjun   33  Bengaluru   20000.0
1        Sujal   25      Delhi  550000.0
2         Koti   38  Bengaluru  119250.0
3         Sank   30    Chennai   40000.0
4      Prajwal   23     Mumbai   78000.0
5         Abhi   58      Delhi  119250.0
6       Harsha   27  Bengaluru   66000.0
7        Geeta   32      Delhi   50000.0
8         Jaya   45  Bengaluru  100000.0
9     Rakshith   25      Delhi   50000.0

In [84]:
duplicate_df = df.drop_duplicates()
duplicate_df

          Name  Age       City    Salary
0  Mallikarjun   33  Bengaluru   20000.0
1        Sujal   25      Delhi  550000.0
2         Koti   38  Bengaluru  119250.0
3         Sank   30    Chennai   40000.0
4      Prajwal   23     Mumbai   78000.0
5         Abhi   58      Delhi  119250.0
6       Harsha   27  Bengaluru   66000.0
7        Geeta   32      Delhi   50000.0
8         Jaya   45  Bengaluru  100000.0
9     Rakshith   25      Delhi   50000.0